[profile.default]
solc = '0.8.21'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = []
optimizer_runs = 4_294_967_295
fs_permissions = []

[fuzz]
runs = 1_000
max_test_rejects = 1_000_000

[profile.optimized]
via_ir = true
out = 'optimized-out'
script = 'contracts'
bytecode_hash = 'none'
test = 'contracts'

[profile.test]
src = 'test/foundry'

[profile.test.fuzz]
runs = 1_000

[profile.lite]
out = 'optimized-out'

[profile.debug]
src = 'contracts'
optimizer = false

[profile.moat_debug]
optimizer = false
test = 'test/foundry/new'

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options
# https://github.com/gakonst/foundry/tree/master/config
